# Generated by Django 4.0.3 on 2022-03-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Certificação')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.PositiveIntegerField(verbose_name='Telefone')),
                ('email', models.CharField(max_length=200, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('fantasy_name', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('cep_production', models.CharField(max_length=9, verbose_name='Cep endereço de produção')),
                ('cep_comerce', models.CharField(max_length=9, verbose_name='Cep endereço de comercio')),
                ('address_number_production', models.PositiveIntegerField(verbose_name='Número endereço de produção')),
                ('address_number_comerce', models.PositiveIntegerField(verbose_name='Número endereço de comercio')),
                ('collective_or_individual', models.BooleanField(verbose_name='Produção coletiva ou individual')),
                ('cpf_cnpj', models.CharField(max_length=14, verbose_name='CPF/CNPJ')),
                ('have_certification', models.BooleanField(verbose_name='Certificação')),
                ('ecological', models.BooleanField(verbose_name='Produção Ecologica')),
                ('ecological_certification', models.BooleanField(verbose_name='Certificação Ecologica')),
                ('organic', models.BooleanField(verbose_name='Organico')),
                ('payment', models.TextField(verbose_name='Métodos de pagamento')),
                ('indigenous_recognizing', models.BooleanField(verbose_name='Reconhecimento indigena')),
                ('quilombola_recognizing', models.BooleanField(verbose_name='Reconhecimento Quilombola')),
                ('state', models.CharField(max_length=20, verbose_name='Estado')),
                ('region', models.CharField(max_length=50, verbose_name='Região')),
                ('singup_date', models.DateTimeField()),
                ('items_sold', models.CharField(max_length=1000)),
                ('certifications', models.ManyToManyField(to='signup.certifications')),
                ('contact', models.ManyToManyField(to='signup.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=9)),
                ('house_num', models.PositiveIntegerField()),
                ('singup_date', models.DateTimeField()),
                ('contact', models.ManyToManyField(to='signup.contact')),
            ],
        ),
    ]
